<?php

use Illuminate\Database\Seeder;
use App\City;

class CitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    $subTypeTask=  [
['city' => 'El Encanto', 'state_id' => 1],
['city' => 'La Chorrera', 'state_id' => 1],
['city' => 'La Pedrera', 'state_id' => 1],
['city' => 'La Victoria', 'state_id' => 1],
['city' => 'Leticia', 'state_id' => 1],
['city' => 'Mirití-Paraná', 'state_id' => 1],
['city' => 'Puerto Alegría', 'state_id' => 1],
['city' => 'Puerto Arica', 'state_id' => 1],
['city' => 'Puerto Nariño', 'state_id' => 1],
['city' => 'Puerto Santander', 'state_id' => 1],
['city' => 'Tarapacá', 'state_id' => 1],
['city' => 'Medellín', 'state_id' => 2],
['city' => 'Bello', 'state_id' => 2],
['city' => 'Itagüí', 'state_id' => 2],
['city' => 'Envigado', 'state_id' => 2],
['city' => 'Apartadó', 'state_id' => 2],
['city' => 'Arauca', 'state_id' => 3],
['city' => 'Arauquita', 'state_id' => 3],
['city' => 'Cravo Norte', 'state_id' => 3],
['city' => 'Fortul', 'state_id' => 3],
['city' => 'Puerto Nariño', 'state_id' => 3],
['city' => 'Puerto Rondón', 'state_id' => 3],
['city' => 'Saravena', 'state_id' => 3],
['city' => 'Tame', 'state_id' => 3],
['city' => 'Barranquilla', 'state_id' => 4],
['city' => 'Baranoa', 'state_id' => 4],
['city' => 'Campo de la Cruz', 'state_id' => 4],
['city' => 'Candelaria', 'state_id' => 4],
['city' => 'Galapa', 'state_id' => 4],
['city' => 'Juan de Acosta', 'state_id' => 4],
['city' => 'Luruaco', 'state_id' => 4],
['city' => 'Malambo', 'state_id' => 4],
['city' => 'Manatí', 'state_id' => 4],
['city' => 'Palmar de Varela', 'state_id' => 4],
['city' => 'Piojó', 'state_id' => 4],
['city' => 'Polonuevo', 'state_id' => 4],
['city' => 'Ponedera', 'state_id' => 4],
['city' => 'Puerto Colombia', 'state_id' => 4],
['city' => 'Repelón', 'state_id' => 4],
['city' => 'Sabanagrande', 'state_id' => 4],
['city' => 'Sabanalarga', 'state_id' => 4],
['city' => 'Santa Lucía', 'state_id' => 4],
['city' => 'Santo Tomás', 'state_id' => 4],
['city' => 'Soledad', 'state_id' => 4],
['city' => 'Suán', 'state_id' => 4],
['city' => 'Tubará', 'state_id' => 4],
['city' => 'siacurí', 'state_id' => 4],
['city' => 'Bogotá', 'state_id' => 5],
['city' => 'Achí', 'state_id' => 6],
['city' => 'Altos del Rosario', 'state_id' => 6],
['city' => 'Arenal', 'state_id' => 6],
['city' => 'Arjona', 'state_id' => 6],
['city' => 'Arroyohondo', 'state_id' => 6],
['city' => 'Barranco de Loba', 'state_id' => 6],
['city' => 'Calamar', 'state_id' => 6],
['city' => 'Cantagallo', 'state_id' => 6],
['city' => 'El Carmen de Bolívar', 'state_id' => 6],
['city' => 'Cartagena de Indias', 'state_id' => 6],
['city' => 'Cicuco', 'state_id' => 6],
['city' => 'Clemencia', 'state_id' => 6],
['city' => 'Córdoba', 'state_id' => 6],
['city' => 'El Guamo', 'state_id' => 6],
['city' => 'El Peñón', 'state_id' => 6],
['city' => 'Hatillo de Loba', 'state_id' => 6],
['city' => 'Magangué', 'state_id' => 6],
['city' => 'Mahates', 'state_id' => 6],
['city' => 'Margarita', 'state_id' => 6],
['city' => 'María La Baja', 'state_id' => 6],
['city' => 'Montecristo', 'state_id' => 6],
['city' => 'Morales', 'state_id' => 6],
['city' => 'Norosí', 'state_id' => 6],
['city' => 'Pinillos', 'state_id' => 6],
['city' => 'Regidor', 'state_id' => 6],
['city' => 'Río Viejo', 'state_id' => 6],
['city' => 'San Cristóbal', 'state_id' => 6],
['city' => 'San Estanislao', 'state_id' => 6],
['city' => 'San Fernando', 'state_id' => 6],
['city' => 'San Jacinto', 'state_id' => 6],
['city' => 'San Jacinto del Cauca', 'state_id' => 6],
['city' => 'San Juan Nepomuceno', 'state_id' => 6],
['city' => 'San Martín de Loba', 'state_id' => 6],
['city' => 'San Pablo', 'state_id' => 6],
['city' => 'Santa Catalina', 'state_id' => 6],
['city' => 'Santa Cruz de Mompox', 'state_id' => 6],
['city' => 'Santa Rosa', 'state_id' => 6],
['city' => 'Santa Rosa del Sur', 'state_id' => 6],
['city' => 'Simití', 'state_id' => 6],
['city' => 'Soplaviento', 'state_id' => 6],
['city' => 'Talaigua Nuevo', 'state_id' => 6],
['city' => 'Tiquisio', 'state_id' => 6],
['city' => 'Turbaco', 'state_id' => 6],
['city' => 'Turbaná', 'state_id' => 6],
['city' => 'Villanueva', 'state_id' => 6],
['city' => 'Zambrano', 'state_id' => 6],
['city' => 'Chíquiza', 'state_id' => 7],
['city' => 'Chivatá', 'state_id' => 7],
['city' => 'Cómbita', 'state_id' => 7],
['city' => 'Cucaita', 'state_id' => 7],
['city' => 'Motavita', 'state_id' => 7],
['city' => 'Oicatá', 'state_id' => 7],
['city' => 'Samacá', 'state_id' => 7],
['city' => 'Siachoque', 'state_id' => 7],
['city' => 'Sora', 'state_id' => 7],
['city' => 'Soracá', 'state_id' => 7],
['city' => 'Sotaquirá', 'state_id' => 7],
['city' => 'Toca', 'state_id' => 7],
['city' => 'Tunja', 'state_id' => 7],
['city' => 'Tuta', 'state_id' => 7],
['city' => 'Ventaquemada', 'state_id' => 7],
['city' => 'Chiscas', 'state_id' => 7],
['city' => 'El Cocuy', 'state_id' => 7],
['city' => 'El Espino', 'state_id' => 7],
['city' => 'Guacamayas', 'state_id' => 7],
['city' => 'Güicán', 'state_id' => 7],
['city' => 'Panqueba', 'state_id' => 7],
['city' => 'Labranzagrande', 'state_id' => 7],
['city' => 'Pajarito', 'state_id' => 7],
['city' => 'Paya', 'state_id' => 7],
['city' => 'Pisba', 'state_id' => 7],
['city' => 'Berbeo', 'state_id' => 7],
['city' => 'Campohermoso', 'state_id' => 7],
['city' => 'Miraflores', 'state_id' => 7],
['city' => 'Páez', 'state_id' => 7],
['city' => 'San Eduardo', 'state_id' => 7],
['city' => 'Zetaquira', 'state_id' => 7],
['city' => 'Boyacá', 'state_id' => 7],
['city' => 'Ciénega', 'state_id' => 7],
['city' => 'Jenesano', 'state_id' => 7],
['city' => 'Nuevo Colón', 'state_id' => 7],
['city' => 'Ramiriquí', 'state_id' => 7],
['city' => 'Rondón', 'state_id' => 7],
['city' => 'Tibaná', 'state_id' => 7],
['city' => 'Turmequé', 'state_id' => 7],
['city' => 'Úmbita', 'state_id' => 7],
['city' => 'Viracachá', 'state_id' => 7],
['city' => 'Chinavita', 'state_id' => 7],
['city' => 'Garagoa', 'state_id' => 7],
['city' => 'Macanal', 'state_id' => 7],
['city' => 'Pachavita', 'state_id' => 7],
['city' => 'San Luis de Gaceno', 'state_id' => 7],
['city' => 'Santa María	Neira', 'state_id' => 7],
['city' => 'Boavita	Norte', 'state_id' => 7],
['city' => 'Covarachía', 'state_id' => 7],
['city' => 'La Uvita', 'state_id' => 7],
['city' => 'San Mateo', 'state_id' => 7],
['city' => 'Sativanorte', 'state_id' => 7],
['city' => 'Sativasur', 'state_id' => 7],
['city' => 'Soatá', 'state_id' => 7],
['city' => 'Susacón', 'state_id' => 7],
['city' => 'Tipacoque', 'state_id' => 7],
['city' => 'Briceño', 'state_id' => 7],
['city' => 'Buenavista', 'state_id' => 7],
['city' => 'Caldas', 'state_id' => 7],
['city' => 'Chiquinquirá', 'state_id' => 7],
['city' => 'Coper', 'state_id' => 7],
['city' => 'La Victoria', 'state_id' => 7],
['city' => 'Maripí', 'state_id' => 7],
['city' => 'Muzo', 'state_id' => 7],
['city' => 'Otanche', 'state_id' => 7],
['city' => 'Pauna', 'state_id' => 7],
['city' => 'Quípama', 'state_id' => 7],
['city' => 'Saboyá', 'state_id' => 7],
['city' => 'San Miguel de Sema', 'state_id' => 7],
['city' => 'San Pablo de Borbur', 'state_id' => 7],
['city' => 'Tununguá', 'state_id' => 7],
['city' => 'Almeida', 'state_id' => 7],
['city' => 'Chivor', 'state_id' => 7],
['city' => 'Guateque', 'state_id' => 7],
['city' => 'Guayatá', 'state_id' => 7],
['city' => 'La Capilla', 'state_id' => 7],
['city' => 'Somondoco', 'state_id' => 7],
['city' => 'Sutatenza', 'state_id' => 7],
['city' => 'Tenza', 'state_id' => 7],
['city' => 'Arcabuco', 'state_id' => 7],
['city' => 'Chitaraque', 'state_id' => 7],
['city' => 'Gachantivá', 'state_id' => 7],
['city' => 'Moniquirá', 'state_id' => 7],
['city' => 'Ráquira', 'state_id' => 7],
['city' => 'Sáchica', 'state_id' => 7],
['city' => 'San José de Pare', 'state_id' => 7],
['city' => 'Santa Sofía', 'state_id' => 7],
['city' => 'Santana', 'state_id' => 7],
['city' => 'Sutamarchán', 'state_id' => 7],
['city' => 'Tinjacá', 'state_id' => 7],
['city' => 'Togüí', 'state_id' => 7],
['city' => 'Villa de Leyva', 'state_id' => 7],
['city' => 'Aquitania', 'state_id' => 7],
['city' => 'Cuítiva', 'state_id' => 7],
['city' => 'Firavitoba', 'state_id' => 7],
['city' => 'Gámeza', 'state_id' => 7],
['city' => 'Iza', 'state_id' => 7],
['city' => 'Mongua', 'state_id' => 7],
['city' => 'Monguí', 'state_id' => 7],
['city' => 'Nobsa', 'state_id' => 7],
['city' => 'Pesca', 'state_id' => 7],
['city' => 'Sogamoso', 'state_id' => 7],
['city' => 'Tibasosa', 'state_id' => 7],
['city' => 'Tópaga', 'state_id' => 7],
['city' => 'Tota', 'state_id' => 7],
['city' => 'Belén', 'state_id' => 7],
['city' => 'Busbanzá', 'state_id' => 7],
['city' => 'Cerinza', 'state_id' => 7],
['city' => 'Corrales', 'state_id' => 7],
['city' => 'Duitama', 'state_id' => 7],
['city' => 'Floresta', 'state_id' => 7],
['city' => 'Paipa', 'state_id' => 7],
['city' => 'Santa Rosa de Viterbo', 'state_id' => 7],
['city' => 'Tutazá', 'state_id' => 7],
['city' => 'Betéitiva', 'state_id' => 7],
['city' => 'Chita', 'state_id' => 7],
['city' => 'Jericó', 'state_id' => 7],
['city' => 'Paz de Río', 'state_id' => 7],
['city' => 'Socha', 'state_id' => 7],
['city' => 'Socotá', 'state_id' => 7],
['city' => 'Tasco', 'state_id' => 7],
['city' => 'Cubará', 'state_id' => 7],
['city' => 'Puerto Boyacá', 'state_id' => 7],
['city' => 'Aguadas', 'state_id' => 8],
['city' => 'Anserma', 'state_id' => 8],
['city' => 'Aranzazu', 'state_id' => 8],
['city' => 'Belalcazar', 'state_id' => 8],
['city' => 'Chinchiná', 'state_id' => 8],
['city' => 'Filadelfia', 'state_id' => 8],
['city' => 'La Dorada', 'state_id' => 8],
['city' => 'La Merced', 'state_id' => 8],
['city' => 'Manizales', 'state_id' => 8],
['city' => 'Manzanares', 'state_id' => 8],
['city' => 'Marmato', 'state_id' => 8],
['city' => 'Marquetalia', 'state_id' => 8],
['city' => 'Marulanda', 'state_id' => 8],
['city' => 'Neira', 'state_id' => 8],
['city' => 'Norcasia', 'state_id' => 8],
['city' => 'Pacora', 'state_id' => 8],
['city' => 'Palestina', 'state_id' => 8],
['city' => 'Pensilvania', 'state_id' => 8],
['city' => 'Riosucio', 'state_id' => 8],
['city' => 'Risaralda', 'state_id' => 8],
['city' => 'Salamina', 'state_id' => 8],
['city' => 'Samana', 'state_id' => 8],
['city' => 'San Jose', 'state_id' => 8],
['city' => 'Supía', 'state_id' => 8],
['city' => 'Victoria', 'state_id' => 8],
['city' => 'Villamaría', 'state_id' => 8],
['city' => 'Viterbo', 'state_id' => 8],
['city' => 'Albania', 'state_id' => 9],
['city' => 'Belén de los Andaquies', 'state_id' => 9],
['city' => 'Cartagena del Chairá', 'state_id' => 9],
['city' => 'Currillo', 'state_id' => 9],
['city' => 'El Doncello', 'state_id' => 9],
['city' => 'El Paujil', 'state_id' => 9],
['city' => 'Florencia', 'state_id' => 9],
['city' => 'La Montañita', 'state_id' => 9],
['city' => 'Morelia', 'state_id' => 9],
['city' => 'Puerto Milán', 'state_id' => 9],
['city' => 'Puerto Rico', 'state_id' => 9],
['city' => 'San José del Fragua', 'state_id' => 9],
['city' => 'San Vicente del Caguán', 'state_id' => 9],
['city' => 'Solano', 'state_id' => 9],
['city' => 'Solita', 'state_id' => 9],
['city' => 'Valparaíso', 'state_id' => 9],
['city' => 'Aguazul', 'state_id' => 10],
['city' => 'Chámeza', 'state_id' => 10],
['city' => 'Hato Corozal', 'state_id' => 10],
['city' => 'La Salina', 'state_id' => 10],
['city' => 'Maní', 'state_id' => 10],
['city' => 'Monterrey', 'state_id' => 10],
['city' => 'Nunchía', 'state_id' => 10],
['city' => 'Orocué', 'state_id' => 10],
['city' => 'Paz de Ariporo', 'state_id' => 10],
['city' => 'Pore', 'state_id' => 10],
['city' => 'Recetor', 'state_id' => 10],
['city' => 'Sabanalarga', 'state_id' => 10],
['city' => 'Sácama', 'state_id' => 10],
['city' => 'San Luis de Palenque', 'state_id' => 10],
['city' => 'Támara', 'state_id' => 10],
['city' => 'Tauramena', 'state_id' => 10],
['city' => 'Trinidad', 'state_id' => 10],
['city' => 'Villanueva', 'state_id' => 10],
['city' => 'Yopal', 'state_id' => 10],
['city' => 'Buenos Aires', 'state_id' => 11],
['city' => 'Caloto', 'state_id' => 11],
['city' => 'Corinto', 'state_id' => 11],
['city' => 'Guachené', 'state_id' => 11],
['city' => 'Miranda', 'state_id' => 11],
['city' => 'Padilla', 'state_id' => 11],
['city' => 'Puerto Tejada', 'state_id' => 11],
['city' => 'Santander de Quilichao', 'state_id' => 11],
['city' => 'Suárez', 'state_id' => 11],
['city' => 'Villa Rica', 'state_id' => 11],
['city' => 'Cajibío', 'state_id' => 11],
['city' => 'El Tambo', 'state_id' => 11],
['city' => 'La Sierra', 'state_id' => 11],
['city' => 'Morales', 'state_id' => 11],
['city' => 'Piendamó', 'state_id' => 11],
['city' => 'Popayán', 'state_id' => 11],
['city' => 'Rosas', 'state_id' => 11],
['city' => 'Sotará', 'state_id' => 11],
['city' => 'Timbío', 'state_id' => 11],
['city' => 'Almaguer', 'state_id' => 11],
['city' => 'Argelia', 'state_id' => 11],
['city' => 'Balboa', 'state_id' => 11],
['city' => 'Bolívar', 'state_id' => 11],
['city' => 'Florencia', 'state_id' => 11],
['city' => 'La Vega', 'state_id' => 11],
['city' => 'Mercaderes', 'state_id' => 11],
['city' => 'Patía', 'state_id' => 11],
['city' => 'Piamonte', 'state_id' => 11],
['city' => 'San Sebastián', 'state_id' => 11],
['city' => 'Santa Rosa', 'state_id' => 11],
['city' => 'Sucre', 'state_id' => 11],
['city' => 'Guapí', 'state_id' => 11],
['city' => 'López de Micay', 'state_id' => 11],
['city' => 'Timbiquí', 'state_id' => 11],
['city' => 'Caldono', 'state_id' => 11],
['city' => 'Inzá', 'state_id' => 11],
['city' => 'Jambaló', 'state_id' => 11],
['city' => 'Páez', 'state_id' => 11],
['city' => 'Puracé (Coconuco)', 'state_id' => 11],
['city' => 'Silvia', 'state_id' => 11],
['city' => 'Toribío', 'state_id' => 11],
['city' => 'Totoró', 'state_id' => 11],
['city' => 'Valledupar', 'state_id' => 12],
['city' => 'Aguachica', 'state_id' => 12],
['city' => 'Agustín Codazzi', 'state_id' => 12],
['city' => 'Bosconia', 'state_id' => 12],
['city' => 'Chimichagua', 'state_id' => 12],
['city' => 'El Copey', 'state_id' => 12],
['city' => 'San Alberto', 'state_id' => 12],
['city' => 'Curumaní', 'state_id' => 12],
['city' => 'El Paso', 'state_id' => 12],
['city' => 'La Paz', 'state_id' => 12],
['city' => 'Pueblo Bello', 'state_id' => 12],
['city' => 'La Jagua de Ibirico', 'state_id' => 12],
['city' => 'Chiriguaná', 'state_id' => 12],
['city' => 'Astrea', 'state_id' => 12],
['city' => 'San Martín', 'state_id' => 12],
['city' => 'Pelaya', 'state_id' => 12],
['city' => 'Pailitas', 'state_id' => 12],
['city' => 'Gamarra', 'state_id' => 12],
['city' => 'Manaure Balcón del Cesar', 'state_id' => 12],
['city' => 'Río de Oro', 'state_id' => 12],
['city' => 'Tamalameque', 'state_id' => 12],
['city' => 'Becerril', 'state_id' => 12],
['city' => 'San Diego', 'state_id' => 12],
['city' => 'La Gloria', 'state_id' => 12],
['city' => 'González', 'state_id' => 12],
['city' => 'Cesar', 'state_id' => 12],
['city' => 'Acandí', 'state_id' => 13],
['city' => 'Alto Baudó', 'state_id' => 13],
['city' => 'Atrato', 'state_id' => 13],
['city' => 'Bagadó', 'state_id' => 13],
['city' => 'Bahía Solano', 'state_id' => 13],
['city' => 'Bajo Baudó', 'state_id' => 13],
['city' => 'Bojayá', 'state_id' => 13],
['city' => 'Carmen del Atrato', 'state_id' => 13],
['city' => 'Certegui', 'state_id' => 13],
['city' => 'Condoto', 'state_id' => 13],
['city' => 'El Carmen del Darién', 'state_id' => 13],
['city' => 'Itsmina', 'state_id' => 13],
['city' => 'Juradó', 'state_id' => 13],
['city' => 'Litoral de San Juan', 'state_id' => 13],
['city' => 'Lloró', 'state_id' => 13],
['city' => 'Medio Atrato', 'state_id' => 13],
['city' => 'Medio Baudo', 'state_id' => 13],
['city' => 'Medio San Juan', 'state_id' => 13],
['city' => 'Nóvita', 'state_id' => 13],
['city' => 'Nuquí', 'state_id' => 13],
['city' => 'Quibdó', 'state_id' => 13],
['city' => 'Río Iró', 'state_id' => 13],
['city' => 'Rio Quito', 'state_id' => 13],
['city' => 'Riosucio', 'state_id' => 13],
['city' => 'San José del Palmar', 'state_id' => 13],
['city' => 'Sipí', 'state_id' => 13],
['city' => 'Tadó', 'state_id' => 13],
['city' => 'Unguía', 'state_id' => 13],
['city' => 'Unión Panamericana', 'state_id' => 13],
['city' => 'Ayapel', 'state_id' => 14],
['city' => 'Buenavista', 'state_id' => 14],
['city' => 'Canalete', 'state_id' => 14],
['city' => 'Cereté', 'state_id' => 14],
['city' => 'Chimá', 'state_id' => 14],
['city' => 'Chinú', 'state_id' => 14],
['city' => 'Ciénaga de Oro', 'state_id' => 14],
['city' => 'Cotorra', 'state_id' => 14],
['city' => 'La Apartada', 'state_id' => 14],
['city' => 'Los Córdobas', 'state_id' => 14],
['city' => 'Momil', 'state_id' => 14],
['city' => 'Montelíbano', 'state_id' => 14],
['city' => 'Montería', 'state_id' => 14],
['city' => 'Moñitos', 'state_id' => 14],
['city' => 'Planeta Rica', 'state_id' => 14],
['city' => 'Pueblo Nuevo', 'state_id' => 14],
['city' => 'Puerto Escondido', 'state_id' => 14],
['city' => 'Puerto Libertador', 'state_id' => 14],
['city' => 'Purísima', 'state_id' => 14],
['city' => 'Sahagún', 'state_id' => 14],
['city' => 'San Andrés de Sotavento', 'state_id' => 14],
['city' => 'San Antero', 'state_id' => 14],
['city' => 'San Bernardo del Viento', 'state_id' => 14],
['city' => 'San Carlos', 'state_id' => 14],
['city' => 'San José de Uré', 'state_id' => 14],
['city' => 'San Pelayo', 'state_id' => 14],
['city' => 'Santa Cruz de Lorica', 'state_id' => 14],
['city' => 'Tierralta', 'state_id' => 14],
['city' => 'Tuchín', 'state_id' => 14],
['city' => 'Valencia', 'state_id' => 14],
['city' => 'Chocontá', 'state_id' => 15],
['city' => 'Machetá', 'state_id' => 15],
['city' => 'Manta', 'state_id' => 15],
['city' => 'Sesquilé', 'state_id' => 15],
['city' => 'Suesca', 'state_id' => 15],
['city' => 'Tibirita', 'state_id' => 15],
['city' => 'Villapinzón', 'state_id' => 15],
['city' => 'Agua de Dios', 'state_id' => 15],
['city' => 'Girardot', 'state_id' => 15],
['city' => 'Guataquí', 'state_id' => 15],
['city' => 'Jerusalén', 'state_id' => 15],
['city' => 'Nariño', 'state_id' => 15],
['city' => 'Nilo', 'state_id' => 15],
['city' => 'Ricaurte', 'state_id' => 15],
['city' => 'Tocaima', 'state_id' => 15],
['city' => 'Caparrapí', 'state_id' => 15],
['city' => 'Guaduas', 'state_id' => 15],
['city' => 'Puerto Salgar', 'state_id' => 15],
['city' => 'Albán', 'state_id' => 15],
['city' => 'La Peña', 'state_id' => 15],
['city' => 'La Vega', 'state_id' => 15],
['city' => 'Nimaima', 'state_id' => 15],
['city' => 'Nocaima', 'state_id' => 15],
['city' => 'Quebradanegra', 'state_id' => 15],
['city' => 'San Francisco', 'state_id' => 15],
['city' => 'Sasaima', 'state_id' => 15],
['city' => 'Supatá', 'state_id' => 15],
['city' => 'Útica', 'state_id' => 15],
['city' => 'Vergara', 'state_id' => 15],
['city' => 'Villeta', 'state_id' => 15],
['city' => 'Gachalá', 'state_id' => 15],
['city' => 'Gachetá', 'state_id' => 15],
['city' => 'Gama', 'state_id' => 15],
['city' => 'Guasca', 'state_id' => 15],
['city' => 'Guatavita', 'state_id' => 15],
['city' => 'Junín', 'state_id' => 15],
['city' => 'La Calera', 'state_id' => 15],
['city' => 'Ubalá', 'state_id' => 15],
['city' => 'Beltrán', 'state_id' => 15],
['city' => 'Bituima', 'state_id' => 15],
['city' => 'Chaguaní', 'state_id' => 15],
['city' => 'Guayabal de Síquima', 'state_id' => 15],
['city' => 'Pulí', 'state_id' => 15],
['city' => 'San Juan de Rioseco', 'state_id' => 15],
['city' => 'Vianí', 'state_id' => 15],
['city' => 'Medina', 'state_id' => 15],
['city' => 'Paratebueno', 'state_id' => 15],
['city' => 'Cáqueza', 'state_id' => 15],
['city' => 'Chipaque', 'state_id' => 15],
['city' => 'Choachí', 'state_id' => 15],
['city' => 'Fómeque', 'state_id' => 15],
['city' => 'Fosca', 'state_id' => 15],
['city' => 'Guayabetal', 'state_id' => 15],
['city' => 'Gutiérrez', 'state_id' => 15],
['city' => 'Quetame', 'state_id' => 15],
['city' => 'Ubaque', 'state_id' => 15],
['city' => 'Une', 'state_id' => 15],
['city' => 'El Peñón', 'state_id' => 15],
['city' => 'La Palma', 'state_id' => 15],
['city' => 'Pacho', 'state_id' => 15],
['city' => 'Paime', 'state_id' => 15],
['city' => 'San Cayetano', 'state_id' => 15],
['city' => 'Topaipí', 'state_id' => 15],
['city' => 'Villagómez', 'state_id' => 15],
['city' => 'Yacopí', 'state_id' => 15],
['city' => 'Cajicá', 'state_id' => 15],
['city' => 'Chía', 'state_id' => 15],
['city' => 'Cogua', 'state_id' => 15],
['city' => 'Gachancipá', 'state_id' => 15],
['city' => 'Nemocón', 'state_id' => 15],
['city' => 'Sopó', 'state_id' => 15],
['city' => 'Tabio', 'state_id' => 15],
['city' => 'Tenjo', 'state_id' => 15],
['city' => 'Tocancipá', 'state_id' => 15],
['city' => 'Zipaquirá', 'state_id' => 15],
['city' => 'Bojacá', 'state_id' => 15],
['city' => 'Cota', 'state_id' => 15],
['city' => 'El Rosal', 'state_id' => 15],
['city' => 'Facatativá', 'state_id' => 15],
['city' => 'Funza', 'state_id' => 15],
['city' => 'Madrid', 'state_id' => 15],
['city' => 'Mosquera', 'state_id' => 15],
['city' => 'Subachoque', 'state_id' => 15],
['city' => 'Zipacón', 'state_id' => 15],
['city' => 'Sibaté', 'state_id' => 15],
['city' => 'Soacha', 'state_id' => 15],
['city' => 'Arbeláez', 'state_id' => 15],
['city' => 'Cabrera', 'state_id' => 15],
['city' => 'Fusagasugá', 'state_id' => 15],
['city' => 'Granada', 'state_id' => 15],
['city' => 'Pandi', 'state_id' => 15],
['city' => 'Pasca', 'state_id' => 15],
['city' => 'San Bernardo', 'state_id' => 15],
['city' => 'Silvania', 'state_id' => 15],
['city' => 'Tibacuy', 'state_id' => 15],
['city' => 'Venecia', 'state_id' => 15],
['city' => 'Anapoima', 'state_id' => 15],
['city' => 'Anolaima', 'state_id' => 15],
['city' => 'Apulo', 'state_id' => 15],
['city' => 'Cachipay', 'state_id' => 15],
['city' => 'El Colegio', 'state_id' => 15],
['city' => 'La Mesa', 'state_id' => 15],
['city' => 'Quipile', 'state_id' => 15],
['city' => 'San Antonio del Tequendama', 'state_id' => 15],
['city' => 'Tena', 'state_id' => 15],
['city' => 'Viotá', 'state_id' => 15],
['city' => 'Carmen de Carupa', 'state_id' => 15],
['city' => 'Cucunubá', 'state_id' => 15],
['city' => 'Fúquene', 'state_id' => 15],
['city' => 'Guachetá', 'state_id' => 15],
['city' => 'Lenguazaque', 'state_id' => 15],
['city' => 'Simijaca', 'state_id' => 15],
['city' => 'Susa', 'state_id' => 15],
['city' => 'Sutatausa', 'state_id' => 15],
['city' => 'Tausa', 'state_id' => 15],
['city' => 'Ubaté', 'state_id' => 15],
['city' => 'Barrancominas', 'state_id' => 16],
['city' => 'Cacahual', 'state_id' => 16],
['city' => 'Inírida', 'state_id' => 16],
['city' => 'La Guadalupe', 'state_id' => 16],
['city' => 'Mapiripana', 'state_id' => 16],
['city' => 'Morichal Nuevo', 'state_id' => 16],
['city' => 'Pana Pana', 'state_id' => 16],
['city' => 'Puerto Colombia', 'state_id' => 16],
['city' => 'San Felipe', 'state_id' => 16],
['city' => 'Calamar', 'state_id' => 17],
['city' => 'El Retorno', 'state_id' => 17],
['city' => 'Miraflores', 'state_id' => 17],
['city' => 'San José del Guaviare', 'state_id' => 17],
['city' => 'Aipe', 'state_id' => 18],
['city' => 'Algeciras', 'state_id' => 18],
['city' => 'Baraya', 'state_id' => 18],
['city' => 'Campoalegre', 'state_id' => 18],
['city' => 'Colombia', 'state_id' => 18],
['city' => 'Hobo', 'state_id' => 18],
['city' => 'Íquira', 'state_id' => 18],
['city' => 'Neiva', 'state_id' => 18],
['city' => 'Palermo', 'state_id' => 18],
['city' => 'Rivera', 'state_id' => 18],
['city' => 'Santa María', 'state_id' => 18],
['city' => 'Tello', 'state_id' => 18],
['city' => 'Teruel', 'state_id' => 18],
['city' => 'Villavieja', 'state_id' => 18],
['city' => 'Yaguará', 'state_id' => 18],
['city' => 'Agrado', 'state_id' => 18],
['city' => 'Altamira', 'state_id' => 18],
['city' => 'Garzón', 'state_id' => 18],
['city' => 'Gigante', 'state_id' => 18],
['city' => 'Guadalupe', 'state_id' => 18],
['city' => 'Pital', 'state_id' => 18],
['city' => 'Suaza', 'state_id' => 18],
['city' => 'Tarqui', 'state_id' => 18],
['city' => 'La Argentina', 'state_id' => 18],
['city' => 'La Plata', 'state_id' => 18],
['city' => 'Nátaga', 'state_id' => 18],
['city' => 'Paicol', 'state_id' => 18],
['city' => 'Tesalia', 'state_id' => 18],
['city' => 'Acevedo', 'state_id' => 18],
['city' => 'Elías', 'state_id' => 18],
['city' => 'Isnos', 'state_id' => 18],
['city' => 'Oporapa', 'state_id' => 18],
['city' => 'Palestina', 'state_id' => 18],
['city' => 'Pitalito', 'state_id' => 18],
['city' => 'Saladoblanco', 'state_id' => 18],
['city' => 'San Agustín', 'state_id' => 18],
['city' => 'Timaná', 'state_id' => 18],
['city' => 'Albania', 'state_id' => 19],
['city' => 'Barrancas', 'state_id' => 19],
['city' => 'Dibulla', 'state_id' => 19],
['city' => 'Distracción', 'state_id' => 19],
['city' => 'El Molino', 'state_id' => 19],
['city' => 'Fonseca', 'state_id' => 19],
['city' => 'Hatonuevo', 'state_id' => 19],
['city' => 'La Jagua del Pilar', 'state_id' => 19],
['city' => 'Maicao', 'state_id' => 19],
['city' => 'Manaure', 'state_id' => 19],
['city' => 'Riohacha', 'state_id' => 19],
['city' => 'San Juan del Cesar', 'state_id' => 19],
['city' => 'Uribia', 'state_id' => 19],
['city' => 'Urumita', 'state_id' => 19],
['city' => 'Villanueva', 'state_id' => 19],
['city' => 'Algarrobo', 'state_id' => 20],
['city' => 'Aracataca', 'state_id' => 20],
['city' => 'Ariguaní', 'state_id' => 20],
['city' => 'Cerro de San Antonio', 'state_id' => 20],
['city' => 'Chibolo', 'state_id' => 20],
['city' => 'Ciénaga', 'state_id' => 20],
['city' => 'Concordia', 'state_id' => 20],
['city' => 'El Banco', 'state_id' => 20],
['city' => 'El Piñón', 'state_id' => 20],
['city' => 'El Retén', 'state_id' => 20],
['city' => 'Fundación', 'state_id' => 20],
['city' => 'Guamal', 'state_id' => 20],
['city' => 'Nueva Granada', 'state_id' => 20],
['city' => 'Pedraza', 'state_id' => 20],
['city' => 'Pijiño del Carmen', 'state_id' => 20],
['city' => 'Pivijay', 'state_id' => 20],
['city' => 'Plato', 'state_id' => 20],
['city' => 'Pueblo Viejo', 'state_id' => 20],
['city' => 'Remolino', 'state_id' => 20],
['city' => 'Sabanas de San Ángel', 'state_id' => 20],
['city' => 'Salamina', 'state_id' => 20],
['city' => 'San Sebastián de Buenavista', 'state_id' => 20],
['city' => 'Santa Ana', 'state_id' => 20],
['city' => 'Santa Bárbara', 'state_id' => 20],
['city' => 'Santa Marta', 'state_id' => 20],
['city' => 'San Zenón', 'state_id' => 20],
['city' => 'Sitionuevo', 'state_id' => 20],
['city' => 'Tenerife', 'state_id' => 20],
['city' => 'Zapayán', 'state_id' => 20],
['city' => 'Zona Bananera', 'state_id' => 20],
['city' => 'Acacías', 'state_id' => 21],
['city' => 'Barranca de Upía', 'state_id' => 21],
['city' => 'Cabuyaro', 'state_id' => 21],
['city' => 'Castilla La Nueva', 'state_id' => 21],
['city' => 'Cubarral', 'state_id' => 21],
['city' => 'Cumaral', 'state_id' => 21],
['city' => 'El Calvario', 'state_id' => 21],
['city' => 'El Castillo', 'state_id' => 21],
['city' => 'El Dorado', 'state_id' => 21],
['city' => 'Fuente de Oro', 'state_id' => 21],
['city' => 'Granada', 'state_id' => 21],
['city' => 'Guamal', 'state_id' => 21],
['city' => 'La Macarena', 'state_id' => 21],
['city' => 'La Uribe', 'state_id' => 21],
['city' => 'Lejanías', 'state_id' => 21],
['city' => 'Mapiripán', 'state_id' => 21],
['city' => 'Mesetas', 'state_id' => 21],
['city' => 'Puerto Concordia', 'state_id' => 21],
['city' => 'Puerto Gaitán', 'state_id' => 21],
['city' => 'Puerto Lleras', 'state_id' => 21],
['city' => 'Puerto López', 'state_id' => 21],
['city' => 'Puerto Rico', 'state_id' => 21],
['city' => 'Restrepo', 'state_id' => 21],
['city' => 'San Carlos de Guaroa', 'state_id' => 21],
['city' => 'San Juan de Arama', 'state_id' => 21],
['city' => 'San Juanito', 'state_id' => 21],
['city' => 'San Martín', 'state_id' => 21],
['city' => 'Villavicencio', 'state_id' => 21],
['city' => 'Vista Hermosa', 'state_id' => 21],
['city' => 'Albán', 'state_id' => 22],
['city' => 'Aldana', 'state_id' => 22],
['city' => 'Ancuya', 'state_id' => 22],
['city' => 'Arboleda', 'state_id' => 22],
['city' => 'Barbacoas', 'state_id' => 22],
['city' => 'Belén', 'state_id' => 22],
['city' => 'Buesaco', 'state_id' => 22],
['city' => 'Chachagüí', 'state_id' => 22],
['city' => 'Colón', 'state_id' => 22],
['city' => 'Consaca', 'state_id' => 22],
['city' => 'Contadero', 'state_id' => 22],
['city' => 'Córdoba', 'state_id' => 22],
['city' => 'Cuaspud', 'state_id' => 22],
['city' => 'Cumbal', 'state_id' => 22],
['city' => 'Cumbitara', 'state_id' => 22],
['city' => 'El Charco', 'state_id' => 22],
['city' => 'El Peñol', 'state_id' => 22],
['city' => 'El Rosario', 'state_id' => 22],
['city' => 'El Tablón', 'state_id' => 22],
['city' => 'El Tambo', 'state_id' => 22],
['city' => 'Francisco Pizarro', 'state_id' => 22],
['city' => 'Funes', 'state_id' => 22],
['city' => 'Guachucal', 'state_id' => 22],
['city' => 'Guaitarilla', 'state_id' => 22],
['city' => 'Gualmatán', 'state_id' => 22],
['city' => 'Iles', 'state_id' => 22],
['city' => 'Imues', 'state_id' => 22],
['city' => 'Ipiales', 'state_id' => 22],
['city' => 'La Cruz', 'state_id' => 22],
['city' => 'La Florida', 'state_id' => 22],
['city' => 'La Llanada', 'state_id' => 22],
['city' => 'La Tola', 'state_id' => 22],
['city' => 'La Unión', 'state_id' => 22],
['city' => 'Leiva', 'state_id' => 22],
['city' => 'Linares', 'state_id' => 22],
['city' => 'Los Andes', 'state_id' => 22],
['city' => 'Magui', 'state_id' => 22],
['city' => 'Mallama', 'state_id' => 22],
['city' => 'Mosquera', 'state_id' => 22],
['city' => 'Nariño', 'state_id' => 22],
['city' => 'Olaya Herrera', 'state_id' => 22],
['city' => 'Ospina', 'state_id' => 22],
['city' => 'Pasto', 'state_id' => 22],
['city' => 'Policarpa', 'state_id' => 22],
['city' => 'Potosí', 'state_id' => 22],
['city' => 'Providencia', 'state_id' => 22],
['city' => 'Puerres', 'state_id' => 22],
['city' => 'Pupiales', 'state_id' => 22],
['city' => 'Ricaurte', 'state_id' => 22],
['city' => 'Roberto Payán', 'state_id' => 22],
['city' => 'Samaniego', 'state_id' => 22],
['city' => 'San Bernardo', 'state_id' => 22],
['city' => 'San Lorenzo', 'state_id' => 22],
['city' => 'San Pablo', 'state_id' => 22],
['city' => 'San Pedro de Cartago', 'state_id' => 22],
['city' => 'Sandona', 'state_id' => 22],
['city' => 'Santa Barbara', 'state_id' => 22],
['city' => 'Santacruz', 'state_id' => 22],
['city' => 'Sapuyes', 'state_id' => 22],
['city' => 'Taminango', 'state_id' => 22],
['city' => 'Tangua', 'state_id' => 22],
['city' => 'Tumaco', 'state_id' => 22],
['city' => 'Tuquerres', 'state_id' => 22],
['city' => 'Yacuanquer', 'state_id' => 22],
['city' => 'Arboledas', 'state_id' => 23],
['city' => 'Cucutilla', 'state_id' => 23],
['city' => 'Gramalote', 'state_id' => 23],
['city' => 'Lourdes', 'state_id' => 23],
['city' => 'Salazar de Las Palmas', 'state_id' => 23],
['city' => 'Santiago', 'state_id' => 23],
['city' => 'Villa Caro', 'state_id' => 23],
['city' => 'Cúcuta', 'state_id' => 23],
['city' => 'El Zulia', 'state_id' => 23],
['city' => 'Los Patios', 'state_id' => 23],
['city' => 'Puerto Santander', 'state_id' => 23],
['city' => 'San Cayetano', 'state_id' => 23],
['city' => 'Villa del Rosario', 'state_id' => 23],
['city' => 'Bucarasica', 'state_id' => 23],
['city' => 'El Tarra', 'state_id' => 23],
['city' => 'Sardinata', 'state_id' => 23],
['city' => 'Tibú', 'state_id' => 23],
['city' => 'Ábrego', 'state_id' => 23],
['city' => 'Cáchira', 'state_id' => 23],
['city' => 'Convención', 'state_id' => 23],
['city' => 'El Carmen', 'state_id' => 23],
['city' => 'Hacarí', 'state_id' => 23],
['city' => 'La Esperanza', 'state_id' => 23],
['city' => 'La Playa de Belén', 'state_id' => 23],
['city' => 'Ocaña', 'state_id' => 23],
['city' => 'San Calixto', 'state_id' => 23],
['city' => 'Teorama', 'state_id' => 23],
['city' => 'Cácota', 'state_id' => 23],
['city' => 'Chitagá', 'state_id' => 23],
['city' => 'Mutiscua', 'state_id' => 23],
['city' => 'Pamplona', 'state_id' => 23],
['city' => 'Pamplonita', 'state_id' => 23],
['city' => 'Santo Domingo de Silos', 'state_id' => 23],
['city' => 'Bochalema', 'state_id' => 23],
['city' => 'Chinácota', 'state_id' => 23],
['city' => 'Durania', 'state_id' => 23],
['city' => 'Herrán', 'state_id' => 23],
['city' => 'Labateca', 'state_id' => 23],
['city' => 'Ragonvalia', 'state_id' => 23],
['city' => 'Toledo', 'state_id' => 23],
['city' => 'Colón', 'state_id' => 24],
['city' => 'Mocoa', 'state_id' => 24],
['city' => 'Orito', 'state_id' => 24],
['city' => 'Puerto Asís', 'state_id' => 24],
['city' => 'Puerto Caicedo', 'state_id' => 24],
['city' => 'Puerto Guzmán', 'state_id' => 24],
['city' => 'Puerto Leguízamo', 'state_id' => 24],
['city' => 'San Francisco', 'state_id' => 24],
['city' => 'San Miguel', 'state_id' => 24],
['city' => 'Santiago', 'state_id' => 24],
['city' => 'Sibundoy', 'state_id' => 24],
['city' => 'Valle del Guamuez', 'state_id' => 24],
['city' => 'Villagarzón', 'state_id' => 24],
['city' => 'Armenia', 'state_id' => 25],
['city' => 'Buenavista', 'state_id' => 25],
['city' => 'Calarcá', 'state_id' => 25],
['city' => 'Circasia', 'state_id' => 25],
['city' => 'Córdoba', 'state_id' => 25],
['city' => 'Filandia', 'state_id' => 25],
['city' => 'Génova', 'state_id' => 25],
['city' => 'La Tebaida', 'state_id' => 25],
['city' => 'Montenegro', 'state_id' => 25],
['city' => 'Pijao', 'state_id' => 25],
['city' => 'Quimbaya', 'state_id' => 25],
['city' => 'Salento', 'state_id' => 25],
['city' => 'Apía', 'state_id' => 26],
['city' => 'Balboa', 'state_id' => 26],
['city' => 'Belén de Umbría', 'state_id' => 26],
['city' => 'Dosquebradas', 'state_id' => 26],
['city' => 'Guática', 'state_id' => 26],
['city' => 'La Celia', 'state_id' => 26],
['city' => 'La Virginia', 'state_id' => 26],
['city' => 'Marsella', 'state_id' => 26],
['city' => 'Mistrató', 'state_id' => 26],
['city' => 'Pereira', 'state_id' => 26],
['city' => 'Pueblo Rico', 'state_id' => 26],
['city' => 'Quinchía', 'state_id' => 26],
['city' => 'Santa Rosa de Cabal', 'state_id' => 26],
['city' => 'Santuario', 'state_id' => 26],
['city' => 'San Andres', 'state_id' => 27],
['city' => 'Providencia y Santa Catalina', 'state_id' => 27],
['city' => 'Aguada', 'state_id' => 28],
['city' => 'Albania', 'state_id' => 28],
['city' => 'Aratoca', 'state_id' => 28],
['city' => 'Barbosa', 'state_id' => 28],
['city' => 'Barichara', 'state_id' => 28],
['city' => 'Barrancabermeja', 'state_id' => 28],
['city' => 'Betulia', 'state_id' => 28],
['city' => 'Bolívar', 'state_id' => 28],
['city' => 'Bucaramanga', 'state_id' => 28],
['city' => 'Cabrera', 'state_id' => 28],
['city' => 'California', 'state_id' => 28],
['city' => 'Capitanejo', 'state_id' => 28],
['city' => 'Carcasí', 'state_id' => 28],
['city' => 'Cepitá', 'state_id' => 28],
['city' => 'Cerrito', 'state_id' => 28],
['city' => 'Charalá', 'state_id' => 28],
['city' => 'Charta', 'state_id' => 28],
['city' => 'Chima', 'state_id' => 28],
['city' => 'Chipatá', 'state_id' => 28],
['city' => 'Cimitarra', 'state_id' => 28],
['city' => 'Concepción', 'state_id' => 28],
['city' => 'Confines', 'state_id' => 28],
['city' => 'Contratación', 'state_id' => 28],
['city' => 'Coromoro', 'state_id' => 28],
['city' => 'Curití', 'state_id' => 28],
['city' => 'El Carmen de Chucurí', 'state_id' => 28],
['city' => 'El Guacamayo', 'state_id' => 28],
['city' => 'El Peñón', 'state_id' => 28],
['city' => 'El Playón', 'state_id' => 28],
['city' => 'Encino', 'state_id' => 28],
['city' => 'Enciso', 'state_id' => 28],
['city' => 'Florián', 'state_id' => 28],
['city' => 'Floridablanca', 'state_id' => 28],
['city' => 'Galán', 'state_id' => 28],
['city' => 'Gámbita', 'state_id' => 28],
['city' => 'Girón', 'state_id' => 28],
['city' => 'Guaca', 'state_id' => 28],
['city' => 'Guadalupe', 'state_id' => 28],
['city' => 'Guapotá', 'state_id' => 28],
['city' => 'Guavatá', 'state_id' => 28],
['city' => 'Güepsa', 'state_id' => 28],
['city' => 'Hato', 'state_id' => 28],
['city' => 'Jesús María', 'state_id' => 28],
['city' => 'Jordán', 'state_id' => 28],
['city' => 'La Belleza', 'state_id' => 28],
['city' => 'La Paz', 'state_id' => 28],
['city' => 'Landázuri', 'state_id' => 28],
['city' => 'Lebrija', 'state_id' => 28],
['city' => 'Los Santos', 'state_id' => 28],
['city' => 'Macaravita', 'state_id' => 28],
['city' => 'Málaga', 'state_id' => 28],
['city' => 'Matanza', 'state_id' => 28],
['city' => 'Mogotes', 'state_id' => 28],
['city' => 'Molagavita', 'state_id' => 28],
['city' => 'Ocamonte', 'state_id' => 28],
['city' => 'Oiba', 'state_id' => 28],
['city' => 'Onzaga', 'state_id' => 28],
['city' => 'Palmar', 'state_id' => 28],
['city' => 'Palmas del Socorro', 'state_id' => 28],
['city' => 'Páramo', 'state_id' => 28],
['city' => 'Piedecuesta', 'state_id' => 28],
['city' => 'Pinchote', 'state_id' => 28],
['city' => 'Puente Nacional', 'state_id' => 28],
['city' => 'Puerto Parra', 'state_id' => 28],
['city' => 'Puerto Wilches', 'state_id' => 28],
['city' => 'Rionegro', 'state_id' => 28],
['city' => 'Sabana de Torres', 'state_id' => 28],
['city' => 'San Andrés', 'state_id' => 28],
['city' => 'San Benito', 'state_id' => 28],
['city' => 'San Gil', 'state_id' => 28],
['city' => 'San Joaquín', 'state_id' => 28],
['city' => 'San José de Miranda', 'state_id' => 28],
['city' => 'San Miguel', 'state_id' => 28],
['city' => 'San Vicente de Chucurí', 'state_id' => 28],
['city' => 'Santa Bárbara', 'state_id' => 28],
['city' => 'Santa Helena del Opón', 'state_id' => 28],
['city' => 'Simacota', 'state_id' => 28],
['city' => 'Socorro', 'state_id' => 28],
['city' => 'Suaita', 'state_id' => 28],
['city' => 'Sucre', 'state_id' => 28],
['city' => 'Suratá', 'state_id' => 28],
['city' => 'Tona', 'state_id' => 28],
['city' => 'Valle de San José', 'state_id' => 28],
['city' => 'Vélez', 'state_id' => 28],
['city' => 'Vetas', 'state_id' => 28],
['city' => 'Villanueva', 'state_id' => 28],
['city' => 'Zapatoca', 'state_id' => 28],
['city' => 'Guaranda', 'state_id' => 29],
['city' => 'Majagual', 'state_id' => 29],
['city' => 'Sucre', 'state_id' => 29],
['city' => 'Chalán', 'state_id' => 29],
['city' => 'Colosó', 'state_id' => 29],
['city' => 'Morroa', 'state_id' => 29],
['city' => 'Ovejas', 'state_id' => 29],
['city' => 'Sincelejo', 'state_id' => 29],
['city' => 'Coveñas', 'state_id' => 29],
['city' => 'Palmito', 'state_id' => 29],
['city' => 'San Onofre', 'state_id' => 29],
['city' => 'Santiago de Tolú', 'state_id' => 29],
['city' => 'Tolúviejo', 'state_id' => 29],
['city' => 'Buenavista', 'state_id' => 29],
['city' => 'Corozal', 'state_id' => 29],
['city' => 'El Roble', 'state_id' => 29],
['city' => 'Galeras', 'state_id' => 29],
['city' => 'Los Palmitos', 'state_id' => 29],
['city' => 'Sampués', 'state_id' => 29],
['city' => 'San Juan de Betulia', 'state_id' => 29],
['city' => 'San Pedro', 'state_id' => 29],
['city' => 'Sincé', 'state_id' => 29],
['city' => 'Caimito', 'state_id' => 29],
['city' => 'La Unión', 'state_id' => 29],
['city' => 'San Benito Abad', 'state_id' => 29],
['city' => 'San Marcos', 'state_id' => 29],
['city' => 'Alvarado', 'state_id' => 30],
['city' => 'Anzoátegui', 'state_id' => 30],
['city' => 'Cajamarca', 'state_id' => 30],
['city' => 'Coello', 'state_id' => 30],
['city' => 'Espinal', 'state_id' => 30],
['city' => 'Flandes', 'state_id' => 30],
['city' => 'Ibagué', 'state_id' => 30],
['city' => 'Piedras', 'state_id' => 30],
['city' => 'Rovira', 'state_id' => 30],
['city' => 'San Luis', 'state_id' => 30],
['city' => 'Valle de San Juan', 'state_id' => 30],
['city' => 'Casabianca', 'state_id' => 30],
['city' => 'Herveo', 'state_id' => 30],
['city' => 'Lérida', 'state_id' => 30],
['city' => 'Líbano', 'state_id' => 30],
['city' => 'Murillo', 'state_id' => 30],
['city' => 'Santa Isabel', 'state_id' => 30],
['city' => 'Venadillo', 'state_id' => 30],
['city' => 'Villahermosa', 'state_id' => 30],
['city' => 'Ambalema', 'state_id' => 30],
['city' => 'Armero', 'state_id' => 30],
['city' => 'Falan', 'state_id' => 30],
['city' => 'Fresno', 'state_id' => 30],
['city' => 'Honda', 'state_id' => 30],
['city' => 'Mariquita', 'state_id' => 30],
['city' => 'Palocabildo', 'state_id' => 30],
['city' => 'Carmen de Apicalá', 'state_id' => 30],
['city' => 'Cunday', 'state_id' => 30],
['city' => 'Icononzo', 'state_id' => 30],
['city' => 'Melgar', 'state_id' => 30],
['city' => 'Villarrica', 'state_id' => 30],
['city' => 'Ataco', 'state_id' => 30],
['city' => 'Chaparral', 'state_id' => 30],
['city' => 'Coyaima', 'state_id' => 30],
['city' => 'Natagaima', 'state_id' => 30],
['city' => 'Ortega', 'state_id' => 30],
['city' => 'Planadas', 'state_id' => 30],
['city' => 'Rioblanco', 'state_id' => 30],
['city' => 'Roncesvalles', 'state_id' => 30],
['city' => 'San Antonio', 'state_id' => 30],
['city' => 'Alpujarra', 'state_id' => 30],
['city' => 'Dolores', 'state_id' => 30],
['city' => 'Guamo', 'state_id' => 30],
['city' => 'Prado', 'state_id' => 30],
['city' => 'Purificación', 'state_id' => 30],
['city' => 'Saldaña', 'state_id' => 30],
['city' => 'Suárez', 'state_id' => 30],
['city' => 'Albán', 'state_id' => 31],
['city' => 'Alcalá', 'state_id' => 31],
['city' => 'Andalucía', 'state_id' => 31],
['city' => 'Ansermanuevo', 'state_id' => 31],
['city' => 'Argelia', 'state_id' => 31],
['city' => 'Barragán', 'state_id' => 31],
['city' => 'Bitaco', 'state_id' => 31],
['city' => 'Bolívar', 'state_id' => 31],
['city' => 'Buenaventura', 'state_id' => 31],
['city' => 'Buenos Aires', 'state_id' => 31],
['city' => 'Buga', 'state_id' => 31],
['city' => 'Bugalagrande', 'state_id' => 31],
['city' => 'Caicedonia', 'state_id' => 31],
['city' => 'Cali', 'state_id' => 31],
['city' => 'Calima', 'state_id' => 31],
['city' => 'Candelaria', 'state_id' => 31],
['city' => 'Cartago', 'state_id' => 31],
['city' => 'Ceylan', 'state_id' => 31],
['city' => 'Costa Rica', 'state_id' => 31],
['city' => 'Dagua', 'state_id' => 31],
['city' => 'Dapa', 'state_id' => 31],
['city' => 'Darién', 'state_id' => 31],
['city' => 'El Aguila', 'state_id' => 31],
['city' => 'El Bolo', 'state_id' => 31],
['city' => 'El Cairo', 'state_id' => 31],
['city' => 'El Carmelo', 'state_id' => 31],
['city' => 'El Carmen', 'state_id' => 31],
['city' => 'El Cerrito', 'state_id' => 31],
['city' => 'El Dovio', 'state_id' => 31],
['city' => 'Fenicia', 'state_id' => 31],
['city' => 'Florida', 'state_id' => 31],
['city' => 'Galicia', 'state_id' => 31],
['city' => 'Ginebra', 'state_id' => 31],
['city' => 'Guacarí', 'state_id' => 31],
['city' => 'Jamundí', 'state_id' => 31],
['city' => 'Juachaco', 'state_id' => 31],
['city' => 'La Bocana', 'state_id' => 31],
['city' => 'La Buitrera', 'state_id' => 31],
['city' => 'La Cumbre', 'state_id' => 31],
['city' => 'La Dolores', 'state_id' => 31],
['city' => 'La Iberia', 'state_id' => 31],
['city' => 'La Nubia', 'state_id' => 31],
['city' => 'La Unión', 'state_id' => 31],
['city' => 'La Victoria', 'state_id' => 31],
['city' => 'Ladrilleros', 'state_id' => 31],
['city' => 'Lago Calima', 'state_id' => 31],
['city' => 'Madrigal', 'state_id' => 31],
['city' => 'Obando', 'state_id' => 31],
['city' => 'Palmaseca', 'state_id' => 31],
['city' => 'Palmira', 'state_id' => 31],
['city' => 'Pavas', 'state_id' => 31],
['city' => 'Poblado Campestre', 'state_id' => 31],
['city' => 'Potrerito', 'state_id' => 31],
['city' => 'Pradera', 'state_id' => 31],
['city' => 'Queremal', 'state_id' => 31],
['city' => 'Restrepo', 'state_id' => 31],
['city' => 'Riofrío', 'state_id' => 31],
['city' => 'Roldanillo', 'state_id' => 31],
['city' => 'Rozo', 'state_id' => 31],
['city' => 'Salónica', 'state_id' => 31],
['city' => 'Samaria', 'state_id' => 31],
['city' => 'San Antonio de los Caballeros', 'state_id' => 31],
['city' => 'San Pedro', 'state_id' => 31],
['city' => 'Santa Helena', 'state_id' => 31],
['city' => 'Santa Lucía', 'state_id' => 31],
['city' => 'Sevilla', 'state_id' => 31],
['city' => 'Sonso', 'state_id' => 31],
['city' => 'Tienda Nueva', 'state_id' => 31],
['city' => 'Toro', 'state_id' => 31],
['city' => 'Trujillo', 'state_id' => 31],
['city' => 'Tuluá', 'state_id' => 31],
['city' => 'Ulloa', 'state_id' => 31],
['city' => 'Venecia', 'state_id' => 31],
['city' => 'Versalles', 'state_id' => 31],
['city' => 'Vijes', 'state_id' => 31],
['city' => 'Villagorgona', 'state_id' => 31],
['city' => 'Yotoco', 'state_id' => 31],
['city' => 'Yumbo', 'state_id' => 31],
['city' => 'Zarzal', 'state_id' => 31],
['city' => 'Ameime El Placer', 'state_id' => 31],
['city' => 'Quebrada Nueva', 'state_id' => 31],
['city' => 'Rurales Valle', 'state_id' => 31],
['city' => 'La Marina', 'state_id' => 31],
['city' => 'La Horqueta', 'state_id' => 31],
['city' => 'Bahía Malaga', 'state_id' => 31],
['city' => 'Carurú', 'state_id' => 32],
['city' => 'Mitú', 'state_id' => 32],
['city' => 'Pacoa', 'state_id' => 32],
['city' => 'Papunaua', 'state_id' => 32],
['city' => 'Taraira', 'state_id' => 32],
['city' => 'Yavaraté', 'state_id' => 32],
['city' => 'Cumaribo', 'state_id' => 33],
['city' => 'La Primavera', 'state_id' => 33],
['city' => 'Puerto Carreño', 'state_id' => 33],
['city' => 'Santa Rosalía', 'state_id' => 33]
];
  City::insert($subTypeTask);
    }
}
