<?php

use Illuminate\Database\Seeder;
use App\Subtype;

class SubtypeBooksTableSeeder extends Seeder {

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {
        $states = [
          ['name' => 'Arte Plastica', 'type_id' => 1],
          ['name' => 'Arte Moderna', 'type_id' => 1],
          ['name' => 'Cine', 'type_id' => 1],
          ['name' => 'Teatro', 'type_id' => 1],
          ['name' => 'Musica', 'type_id' => 1],
          ['name' => 'Fotografia', 'type_id' => 1],
          ['name' => 'Cardiologia', 'type_id' => 2],
          ['name' => 'Dermatologia', 'type_id' => 2],
          ['name' => 'Cirugia', 'type_id' => 2],
          ['name' => 'Enfermeria y Nutricion', 'type_id' => 2],
          ['name' => 'Fisiologia', 'type_id' => 2],
          ['name' => 'Ginecologia', 'type_id' => 2],
          ['name' => 'Gerontología', 'type_id' => 2],
          ['name' => 'Hepatología', 'type_id' => 2],
          ['name' => 'Inmunología', 'type_id' => 2],
          ['name' => 'Medicina Alternativa', 'type_id' => 2],
          ['name' => 'Medicina Familiar', 'type_id' => 2],
          ['name' => 'Medicina Interna', 'type_id' => 2],
          ['name' => 'Neumología', 'type_id' => 2],
          ['name' => 'Neurología', 'type_id' => 2],
          ['name' => 'Odontología', 'type_id' => 2],
          ['name' => 'Oftalmología', 'type_id' => 2],
          ['name' => 'Oncología', 'type_id' => 2],
          ['name' => 'Ortopedia', 'type_id' => 2],
          ['name' => 'Patología', 'type_id' => 2],
          ['name' => 'Pediatría Y Neonatología', 'type_id' => 2],
          ['name' => 'Primeros Auxilios', 'type_id' => 2],
          ['name' => 'Salud Pública Auditoría', 'type_id' => 2],
          ['name' => 'Sexología', 'type_id' => 2],
          ['name' => 'Temas Varios De Salud', 'type_id' => 2],
          ['name' => 'Terapias Y Farmacología', 'type_id' => 2],
          ['name' => 'Urgencias Médicas', 'type_id' => 2],
          ['name' => 'Urología', 'type_id' => 2],
          ['name' => 'Biología', 'type_id' => 3],
          ['name' => 'Fisica', 'type_id' => 3],
          ['name' => 'Matematicas', 'type_id' => 3],
          ['name' => 'Ingles', 'type_id' => 3],
          ['name' => 'Educacion Fisica', 'type_id' => 3],
          ['name' => 'Pedagogia', 'type_id' => 3],
          ['name' => 'Sociales e Historia', 'type_id' => 3],
          ['name' => 'Democracia', 'type_id' => 3],
          ['name' => 'Pastoral', 'type_id' => 3],
          ['name' => 'Filosofia', 'type_id' => 3],
          ['name' => 'Quimica', 'type_id' => 3],
          ['name' => 'Español', 'type_id' => 3],
          ['name' => 'Geometria', 'type_id' => 3],
          ['name' => 'Informatica', 'type_id' => 3],
          ['name' => 'Redes', 'type_id' => 3],
          ['name' => 'Diseño de interiores', 'type_id' => 4],
          ['name' => 'Diseño Grafico', 'type_id' => 4],
          ['name' => 'Diseño Industrial', 'type_id' => 4],
          ['name' => 'Diseño de Moda', 'type_id' => 4],
          ['name' => 'Diseño Digital', 'type_id' => 4],
          ['name' => 'Ingenieria de Sistemas', 'type_id' => 5],
          ['name' => 'Ingenieria Industrial', 'type_id' => 5],
          ['name' => 'Ingenieria Civil', 'type_id' => 5],
          ['name' => 'Ingenieria Electronica', 'type_id' => 5],
          ['name' => 'Ingenieria de Sonido', 'type_id' => 5],
          ['name' => 'Ingenieria Aeronautica', 'type_id' => 5],
          ['name' => 'Ingenieria Agronómica', 'type_id' => 5],
          ['name' => 'Ingeniería Ambiental', 'type_id' => 5],
          ['name' => 'Ingeniería Biomédica', 'type_id' => 5],
          ['name' => 'Ingeniería Comercial', 'type_id' => 5],
          ['name' => 'Ingeniería de Procesos', 'type_id' => 5],
          ['name' => 'Ingeniería de Producción', 'type_id' => 5],
          ['name' => 'Ingeniería de Telecomunicaciones', 'type_id' => 5],
          ['name' => 'Ingeniería Eléctrica', 'type_id' => 5],
          ['name' => 'Ingeniería Financiera', 'type_id' => 5],
          ['name' => 'Ingeniería Mecánica', 'type_id' => 5],
          ['name' => 'Ingeniería Mecatrónica', 'type_id' => 5],
          ['name' => 'Ingeniería Metalúrgica', 'type_id' => 5],
          ['name' => 'Ingeniería Química', 'type_id' => 5],
          ['name' => 'Ingeniería Topográfica', 'type_id' => 5],
          ['name' => 'Ingeniería Textil', 'type_id' => 5],
          ['name' => 'Economia', 'type_id' => 6],
          ['name' => 'Contabilidad', 'type_id' => 6],
          ['name' => 'Finanzas', 'type_id' => 6],
          ['name' => 'Administracion', 'type_id' => 6],
          ['name' => 'Secretaria', 'type_id' => 6],
          ['name' => 'Marketing', 'type_id' => 6],
          ['name' => 'Internacional', 'type_id' => 7],
          ['name' => 'Colombiana', 'type_id' => 7],
          ['name' => 'Especialidades', 'type_id' => 7],
          ['name' => 'Cacera', 'type_id' => 7],
          ['name' => 'Comic', 'type_id' => 8],
          ['name' => 'Accion', 'type_id' => 8],
          ['name' => 'Romance', 'type_id' => 8],
          ['name' => 'Terror', 'type_id' => 8],
          ['name' => 'Anime', 'type_id' => 8],
          ['name' => 'Adultos', 'type_id' => 8],
          ['name' => 'Aventura', 'type_id' => 8],
          ['name' => 'Ciencia Ficcion', 'type_id' => 8],
          ['name' => 'Comedia', 'type_id' => 8],
          ['name' => 'Misterio', 'type_id' => 8],
          ['name' => 'Suspenso', 'type_id' => 8],
          ['name' => 'LGTBI', 'type_id' => 8],
          ['name' => 'Football', 'type_id' => 9],
          ['name' => 'Tenis', 'type_id' => 9],
          ['name' => 'Baloncesto', 'type_id' => 9],
          ['name' => 'Balonmano', 'type_id' => 9],
          ['name' => 'Boxeo', 'type_id' => 9],
          ['name' => 'Beisbol', 'type_id' => 9],
          ['name' => 'Ciclismo', 'type_id' => 9],
          ['name' => 'Bolos', 'type_id' => 9],
          ['name' => 'Esqui', 'type_id' => 9],
          ['name' => 'Golf', 'type_id' => 9],
          ['name' => 'Hokey', 'type_id' => 9],
          ['name' => 'Karate', 'type_id' => 9],
          ['name' => 'Lucha', 'type_id' => 9],
          ['name' => 'Natacion', 'type_id' => 9],
          ['name' => 'Patinaje', 'type_id' => 9],
          ['name' => 'Polo', 'type_id' => 9],
          ['name' => 'Remo', 'type_id' => 9],
          ['name' => 'Rugby', 'type_id' => 9],
          ['name' => 'Ajedrez', 'type_id' => 9],
          ['name' => 'Surf', 'type_id' => 9],
          ['name' => 'Arqueria', 'type_id' => 9],
          ['name' => 'Parkour', 'type_id' => 9],
          ['name' => 'Estudios', 'type_id' => 10],
          ['name' => 'Documentales', 'type_id' => 10],
          ['name' => 'Articulos', 'type_id' => 10],
          ['name' => 'Proyectos', 'type_id' => 10],
        ];
        Subtype::insert($states);
    }

}
